In [1]:
import pandas as pd
import numpy as np

In [4]:
courses= pd.read_csv('courses.csv')
deliveries= pd.read_csv('deliveries.csv')
matches= pd.read_csv('matches.csv')
month1= pd.read_csv('reg-month1.csv')
month2= pd.read_csv('reg-month2.csv')
students= pd.read_csv('students.csv')

In [5]:
courses

    course_id       course_name  price
0           1            python   2499
1           2               sql   3499
2           3     data analysis   4999
3           4  machine learning   9999
4           5           tableau   2499
5           6          power bi   1899
6           7          ms sxcel   1599
7           8            pandas   1099
8           9            plotly    699
9          10           pyspark   2499
10         11             Numpy    699
11         12               C++   1299

In [8]:
pd.concat([month1, month2], ignore_index=True)

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3
25           3          5
26          16          7
27          12         10
28          12          1
29          14          9
30           7          7
31           7          2
32          16          3
33          17         10
34          11          8
35          14          6
36          12          5
37          12          7
38          18          8
39           1         10
40           1          9
41           2          5
42           7          6
43          22          5
44          22          6
45          23          9
46          23          5
47          14          4
48          14          1
49          11         10
50          42          9
51          50          8
52          38          1

In [11]:
multi=pd.concat([month1, month2], keys=['month1','month2'])
multi

           student_id  course_id
month1 0           23          1
       1           15          5
       2           18          6
       3           23          4
       4           16          9
       5           18          1
       6            1          1
       7            7          8
       8           22          3
       9           15          1
       10          19          4
       11           1          6
       12           7         10
       13          11          7
       14          13          3
       15          24          4
       16          21          1
       17          16          5
       18          23          3
       19          17          7
       20          23          6
       21          25          1
       22          19          2
       23          25         10
       24           3          3
month2 0            3          5
       1           16          7
       2           12         10
       3           12          1
       4           14          9
       5            7          7
       6            7          2
       7           16          3
       8           17         10
       9           11          8
       10          14          6
       11          12          5
       12          12          7
       13          18          8
       14           1         10
       15           1          9
       16           2          5
       17           7          6
       18          22          5
       19          22          6
       20          23          9
       21          23          5
       22          14          4
       23          14          1
       24          11         10
       25          42          9
       26          50          8
       27          38          1

In [17]:
multi.loc[('month1', 0)]

student_id    23
course_id      1
Name: (month1, 0), dtype: int64