In [1]:
import pandas as pd
import numpy as np

In [8]:
# how to create multiindex object
# 1. pd.MultiIndex.from_tuples()
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
multiindex=pd.MultiIndex.from_tuples(index_val)
multiindex

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [12]:
# 2. pd.MultiIndex.from_product()
pd.MultiIndex.from_product([['cse','ece'],[2019,2020,2021,2022]])

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [13]:
s=pd.Series([1,2,3,4,5,6,7,8], index=multiindex)
s

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [19]:
s['cse']

np.int64(1)

In [15]:
s.unstack() #convert into dataframe

     2019  2020  2021  2022
cse     1     2     3     4
ece     5     6     7     8

In [22]:
branch_df=pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12],
        [113,14],
        [15,16],
    ],
    index=multiindex, columns=['avg_package', 'students']
)
branch_df

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021          113        14
    2022           15        16

In [23]:
branch_df.loc['cse']

      avg_package  students
2019            1         2
2020            3         4
2021            5         6
2022            7         8

In [24]:
branch_df['students']

cse  2019     2
     2020     4
     2021     6
     2022     8
ece  2019    10
     2020    12
     2021    14
     2022    16
Name: students, dtype: int64

In [25]:
# multiindex df from columns perspective
branch_df2 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
    ],
    index = [2019,2020,2021,2022],
    columns = pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)

branch_df2

           delhi               mumbai
     avg_package students avg_package students
2019           1        2           0        0
2020           3        4           0        0
2021           5        6           0        0
2022           7        8           0        0

In [29]:
branch_df2['delhi']['students']

2019    2
2020    4
2021    6
2022    8
Name: students, dtype: int64

In [30]:
# Multiindex df in terms of both cols and index

branch_df3 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
        [9,10,0,0],
        [11,12,0,0],
        [13,14,0,0],
        [15,16,0,0],
    ],
    index = multiindex,
    columns = pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)

branch_df3

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [42]:
branch_df3.unstack()

          delhi                                             mumbai            \
    avg_package                students                avg_package
           2019 2020 2021 2022     2019 2020 2021 2022        2019 2020 2021
cse           1    3    5    7        2    4    6    8           0    0    0
ece           9   11   13   15       10   12   14   16           0    0    0


         students
    2022     2019 2020 2021 2022
cse    0        0    0    0    0
ece    0        0    0    0    0

In [49]:
a=branch_df.stack()
a

cse  2019  avg_package      1
           students         2
     2020  avg_package      3
           students         4
     2021  avg_package      5
           students         6
     2022  avg_package      7
           students         8
ece  2019  avg_package      9
           students        10
     2020  avg_package     11
           students        12
     2021  avg_package    113
           students        14
     2022  avg_package     15
           students        16
dtype: int64

In [50]:
a.loc['cse'][2019]

avg_package    1
students       2
dtype: int64