In [1]:
import pandas as pd
import numpy as np

In [8]:
# how to create multiindex object
# 1. pd.MultiIndex.from_tuples()
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
multiindex=pd.MultiIndex.from_tuples(index_val)
multiindex

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [12]:
# 2. pd.MultiIndex.from_product()
pd.MultiIndex.from_product([['cse','ece'],[2019,2020,2021,2022]])

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [13]:
s=pd.Series([1,2,3,4,5,6,7,8], index=multiindex)
s

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [19]:
s['cse']

np.int64(1)

In [15]:
s.unstack() #convert into dataframe

     2019  2020  2021  2022
cse     1     2     3     4
ece     5     6     7     8

In [22]:
branch_df=pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12],
        [113,14],
        [15,16],
    ],
    index=multiindex, columns=['avg_package', 'students']
)
branch_df

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021          113        14
    2022           15        16

In [23]:
branch_df.loc['cse']

      avg_package  students
2019            1         2
2020            3         4
2021            5         6
2022            7         8

In [24]:
branch_df['students']

cse  2019     2
     2020     4
     2021     6
     2022     8
ece  2019    10
     2020    12
     2021    14
     2022    16
Name: students, dtype: int64

In [25]:
# multiindex df from columns perspective
branch_df2 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
    ],
    index = [2019,2020,2021,2022],
    columns = pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)

branch_df2

           delhi               mumbai
     avg_package students avg_package students
2019           1        2           0        0
2020           3        4           0        0
2021           5        6           0        0
2022           7        8           0        0

In [29]:
branch_df2['delhi']['students']

2019    2
2020    4
2021    6
2022    8
Name: students, dtype: int64

In [30]:
# Multiindex df in terms of both cols and index

branch_df3 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
        [9,10,0,0],
        [11,12,0,0],
        [13,14,0,0],
        [15,16,0,0],
    ],
    index = multiindex,
    columns = pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)

branch_df3

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [42]:
branch_df3.unstack()

          delhi                                             mumbai            \
    avg_package                students                avg_package
           2019 2020 2021 2022     2019 2020 2021 2022        2019 2020 2021
cse           1    3    5    7        2    4    6    8           0    0    0
ece           9   11   13   15       10   12   14   16           0    0    0


         students
    2022     2019 2020 2021 2022
cse    0        0    0    0    0
ece    0        0    0    0    0

In [49]:
a=branch_df.stack()
a

cse  2019  avg_package      1
           students         2
     2020  avg_package      3
           students         4
     2021  avg_package      5
           students         6
     2022  avg_package      7
           students         8
ece  2019  avg_package      9
           students        10
     2020  avg_package     11
           students        12
     2021  avg_package    113
           students        14
     2022  avg_package     15
           students        16
dtype: int64

In [50]:
a.loc['cse'][2019]

avg_package    1
students       2
dtype: int64

In [75]:
#extracting rows
# branch_df3.loc[('cse', 2020)]
# branch_df3.loc[('cse',2019):('ece',2021):2]

branch_df3.iloc[[0,3],[0,3]]

               delhi   mumbai
         avg_package students
cse 2019           1        0
    2022           7        0

In [84]:
#extracting columns
branch_df3['delhi':'mumbai']
branch_df3.iloc[:,::2]

               delhi      mumbai
         avg_package avg_package
cse 2019           1           0
    2020           3           0
    2021           5           0
    2022           7           0
ece 2019           9           0
    2020          11           0
    2021          13           0
    2022          15           0

In [91]:
branch_df3.sort_index(ascending=False)
branch_df3.sort_index(ascending=[False,True])
branch_df3.sort_index(level=0, ascending=False)

               delhi               mumbai
         avg_package students avg_package students
ece 2022          15       16           0        0
    2021          13       14           0        0
    2020          11       12           0        0
    2019           9       10           0        0
cse 2022           7        8           0        0
    2021           5        6           0        0
    2020           3        4           0        0
    2019           1        2           0        0

In [92]:
branch_df3.transpose()

                    cse                 ece
                   2019 2020 2021 2022 2019 2020 2021 2022
delhi  avg_package    1    3    5    7    9   11   13   15
       students       2    4    6    8   10   12   14   16
mumbai avg_package    0    0    0    0    0    0    0    0
       students       0    0    0    0    0    0    0    0

In [95]:
branch_df3.swaplevel(axis=1)

         avg_package students avg_package students
               delhi    delhi      mumbai   mumbai
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [98]:
# melt -> simple example branch
# wide to long

pd.DataFrame({'cse':[120]}).melt()

  variable  value
0      cse    120

In [99]:
pd.DataFrame({'cse':[120],'ece':[100],'mech':[50]}).melt(var_name='branch', value_name='num_students')

  branch  num_students
0    cse           120
1    ece           100
2   mech            50

In [102]:
pd.DataFrame(
    {
        'branch':['cse','ece','mech'],
        '2020':[100,150,60],
        '2021':[120,130,80],
        '2022':[150,140,70]
    }
).melt(id_vars=['branch'],var_name='year',value_name='students')

  branch  year  students
0    cse  2020       100
1    ece  2020       150
2   mech  2020        60
3    cse  2021       120
4    ece  2021       130
5   mech  2021        80
6    cse  2022       150
7    ece  2022       140
8   mech  2022        70

In [104]:
confirmed=pd.read_csv('time_series_covid19_confirmed_global.csv')
deaths=pd.read_csv('time_series_covid19_deaths_global.csv')

In [111]:
death=deaths.melt(id_vars=['Province/State','Country/Region','Lat', 'Long'], var_name='Date', value_name='deaths')
confirm=confirmed.melt(id_vars=['Province/State','Country/Region','Lat', 'Long'], var_name='Date', value_name='num_cases')

In [116]:
confirm.merge(death, on=['Province/State','Country/Region','Lat', 'Long', 'Date'])[['Country/Region', 'Date', 'num_cases', 'deaths']]

              Country/Region     Date  num_cases  deaths
0                Afghanistan  1/22/20          0       0
1                    Albania  1/22/20          0       0
2                    Algeria  1/22/20          0       0
3                    Andorra  1/22/20          0       0
4                     Angola  1/22/20          0       0
...                      ...      ...        ...     ...
311248    West Bank and Gaza   1/2/23     703228    5708
311249  Winter Olympics 2022   1/2/23        535       0
311250                 Yemen   1/2/23      11945    2159
311251                Zambia   1/2/23     334661    4024
311252              Zimbabwe   1/2/23     259981    5637

[311253 rows x 4 columns]