In [24]:
import pandas as pd

**CREATING DATAFRAMES**

In [25]:
student_data=[
    [100,20,50],
    [300,21,11],
    [322,22,4],
    [230,23,12]
]
students=pd.DataFrame(student_data, columns=['iq', 'marks', 'packeg'])
students

    iq  marks  packeg
0  100     20      50
1  300     21      11
2  322     22       4
3  230     23      12

In [26]:
studens_data={
   'iq': [100,20,50],
    'merks':[300,21,11],
    'package':[322,22,4],
   
}
pd.DataFrame(studens_data)

    iq  merks  package
0  100    300      322
1   20     21       22
2   50     11        4

In [27]:
employees=pd.read_csv('forpractice_cvc.csv')
employees

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Job Title,Salary
0,1,101,Shelby,Terrell,Male,elijah57@example.net,9803244242,Games developer,100000
1,2,102,Phillip,Summers,Female,bethany14@example.com,9808364778,Phytotherapist,200000
2,3,103,Kristine,Travis,Male,bthompson@example.com,9830238573,Homeopath,350000
3,4,104,Yesenia,Martinez,Male,kaitlinkaiser@example.com,9843028573,Market researcher,400000
4,5,105,Lori,Todd,Male,buchananmanuel@example.net,9732082954,Veterinary surgeon,230000
5,6,106,Erin,Day,Male,tconner@example.org,9807463847,Waste management officer,240000
6,7,107,Katherine,Buck,Female,conniecowan@example.com,9876056789,Intelligence analyst,200000
7,8,108,Ricardo,Hinton,Male,wyattbishop@example.com,7653456533,Hydrogeologist,23400
8,9,109,Dave,Farrell,Male,nmccann@example.net,9876890345,Lawyer,255555
9,10,110,Isaiah,Downs,Male,virginiaterrell@example.org,9086547543,"Engineer, site",332000
10,11,111,Sheila,Ross,Female,huangcathy@example.com,5397852134,Advertising account executive,220000
11,12,112,Stacy,Newton,Male,rayleroy@example.org,7543326534,Warden/ranger,4200000
12,13,113,Mandy,Blake,Male,jefferynoble@example.org,3734672477,"Scientist, clinical",240000
13,14,114,Bridget,Nash,Female,mercedes44@example.com,2424552444,Social worker,757000
14,15,115,Crystal,Farmer,Male,pmiranda@example.org,2345455555,Agricultural consultant,560000

In [28]:
employees.shape

(15, 9)

In [29]:
employees.dtypes

Index          int64
User Id        int64
First Name    object
Last Name     object
Sex           object
Email         object
Phone          int64
Job Title     object
Salary         int64
dtype: object

In [30]:
employees.index

RangeIndex(start=0, stop=15, step=1)

In [31]:
employees.values

array([[1, 101, 'Shelby', 'Terrell', 'Male', 'elijah57@example.net',
        9803244242, 'Games developer', 100000],
       [2, 102, 'Phillip', 'Summers', 'Female', 'bethany14@example.com',
        9808364778, 'Phytotherapist', 200000],
       [3, 103, 'Kristine', 'Travis', 'Male', 'bthompson@example.com',
        9830238573, 'Homeopath', 350000],
       [4, 104, 'Yesenia', 'Martinez', 'Male',
        'kaitlinkaiser@example.com', 9843028573, 'Market researcher',
        400000],
       [5, 105, 'Lori', 'Todd', 'Male', 'buchananmanuel@example.net',
        9732082954, 'Veterinary surgeon', 230000],
       [6, 106, 'Erin', 'Day', 'Male', 'tconner@example.org', 9807463847,
        'Waste management officer', 240000],
       [7, 107, 'Katherine', 'Buck', 'Female', 'conniecowan@example.com',
        9876056789, 'Intelligence analyst', 200000],
       [8, 108, 'Ricardo', 'Hinton', 'Male', 'wyattbishop@example.com',
        7653456533, 'Hydrogeologist', 23400],
       [9, 109, 'Dave', 'Farrell', 'Male', 'nmccann@example.net',
        9876890345, 'Lawyer', 255555],
       [10, 110, 'Isaiah', 'Downs', 'Male',
        'virginiaterrell@example.org', 9086547543, 'Engineer, site',
        332000],
       [11, 111, 'Sheila', 'Ross', 'Female', 'huangcathy@example.com',
        5397852134, 'Advertising account executive', 220000],
       [12, 112, 'Stacy', 'Newton', 'Male', 'rayleroy@example.org',
        7543326534, 'Warden/ranger', 4200000],
       [13, 113, 'Mandy', 'Blake', 'Male', 'jefferynoble@example.org',
        3734672477, 'Scientist, clinical ', 240000],
       [14, 114, 'Bridget', 'Nash', 'Female', 'mercedes44@example.com',
        2424552444, 'Social worker', 757000],
       [15, 115, 'Crystal', 'Farmer', 'Male', 'pmiranda@example.org',
        2345455555, 'Agricultural consultant', 560000]], dtype=object)

In [32]:
employees.columns

Index(['Index', 'User Id', 'First Name', 'Last Name', 'Sex', 'Email', 'Phone',
       'Job Title', 'Salary'],
      dtype='object')

In [33]:
employees.head(3)

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Job Title,Salary
0,1,101,Shelby,Terrell,Male,elijah57@example.net,9803244242,Games developer,100000
1,2,102,Phillip,Summers,Female,bethany14@example.com,9808364778,Phytotherapist,200000
2,3,103,Kristine,Travis,Male,bthompson@example.com,9830238573,Homeopath,350000

In [34]:
employees.tail()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Job Title,Salary
10,11,111,Sheila,Ross,Female,huangcathy@example.com,5397852134,Advertising account executive,220000
11,12,112,Stacy,Newton,Male,rayleroy@example.org,7543326534,Warden/ranger,4200000
12,13,113,Mandy,Blake,Male,jefferynoble@example.org,3734672477,"Scientist, clinical",240000
13,14,114,Bridget,Nash,Female,mercedes44@example.com,2424552444,Social worker,757000
14,15,115,Crystal,Farmer,Male,pmiranda@example.org,2345455555,Agricultural consultant,560000

In [35]:
employees.sample()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Job Title,Salary
7,8,108,Ricardo,Hinton,Male,wyattbishop@example.com,7653456533,Hydrogeologist,23400

In [36]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Index       15 non-null     int64
 1   User Id     15 non-null     int64
 2   First Name  15 non-null     object
 3   Last Name   15 non-null     object
 4   Sex         15 non-null     object
 5   Email       15 non-null     object
 6   Phone       15 non-null     int64
 7   Job Title   15 non-null     object
 8   Salary      15 non-null     int64
dtypes: int64(4), object(5)
memory usage: 1.2+ KB

In [37]:
employees.describe()

           Index     User Id         Phone        Salary
count  15.000000   15.000000  1.500000e+01  1.500000e+01
mean    8.000000  108.000000  7.784216e+09  5.538637e+05
std     4.472136    4.472136  2.871190e+09  1.024355e+06
min     1.000000  101.000000  2.345456e+09  2.340000e+04
25%     4.500000  104.500000  6.470589e+09  2.100000e+05
50%     8.000000  108.000000  9.732083e+09  2.400000e+05
75%    11.500000  111.500000  9.819302e+09  3.750000e+05
max    15.000000  115.000000  9.876890e+09  4.200000e+06

In [38]:
employees.isnull().sum()

Index         0
User Id       0
First Name    0
Last Name     0
Sex           0
Email         0
Phone         0
Job Title     0
Salary        0
dtype: int64

In [39]:
employees.duplicated().sum()

np.int64(0)

In [40]:
employees.rename(columns={'Phone':'Phone_no'}, inplace=True)

In [41]:
employees

,Index,User Id,First Name,Last Name,Sex,Email,Phone_no,Job Title,Salary
0,1,101,Shelby,Terrell,Male,elijah57@example.net,9803244242,Games developer,100000
1,2,102,Phillip,Summers,Female,bethany14@example.com,9808364778,Phytotherapist,200000
2,3,103,Kristine,Travis,Male,bthompson@example.com,9830238573,Homeopath,350000
3,4,104,Yesenia,Martinez,Male,kaitlinkaiser@example.com,9843028573,Market researcher,400000
4,5,105,Lori,Todd,Male,buchananmanuel@example.net,9732082954,Veterinary surgeon,230000
5,6,106,Erin,Day,Male,tconner@example.org,9807463847,Waste management officer,240000
6,7,107,Katherine,Buck,Female,conniecowan@example.com,9876056789,Intelligence analyst,200000
7,8,108,Ricardo,Hinton,Male,wyattbishop@example.com,7653456533,Hydrogeologist,23400
8,9,109,Dave,Farrell,Male,nmccann@example.net,9876890345,Lawyer,255555
9,10,110,Isaiah,Downs,Male,virginiaterrell@example.org,9086547543,"Engineer, site",332000
10,11,111,Sheila,Ross,Female,huangcathy@example.com,5397852134,Advertising account executive,220000
11,12,112,Stacy,Newton,Male,rayleroy@example.org,7543326534,Warden/ranger,4200000
12,13,113,Mandy,Blake,Male,jefferynoble@example.org,3734672477,"Scientist, clinical",240000
13,14,114,Bridget,Nash,Female,mercedes44@example.com,2424552444,Social worker,757000
14,15,115,Crystal,Farmer,Male,pmiranda@example.org,2345455555,Agricultural consultant,560000

In [42]:
students.mean(axis=1)

0     56.666667
1    110.666667
2    116.000000
3     88.333333
dtype: float64

In [43]:
employees['Job Title']

0                   Games developer
1                    Phytotherapist
2                         Homeopath
3                 Market researcher
4                Veterinary surgeon
5          Waste management officer
6              Intelligence analyst
7                    Hydrogeologist
8                            Lawyer
9                    Engineer, site
10    Advertising account executive
11                    Warden/ranger
12             Scientist, clinical
13                    Social worker
14          Agricultural consultant
Name: Job Title, dtype: object

In [44]:
employees[['User Id', 'First Name', 'Salary']]

    User Id First Name   Salary
0       101     Shelby   100000
1       102    Phillip   200000
2       103   Kristine   350000
3       104    Yesenia   400000
4       105       Lori   230000
5       106       Erin   240000
6       107  Katherine   200000
7       108    Ricardo    23400
8       109       Dave   255555
9       110     Isaiah   332000
10      111     Sheila   220000
11      112      Stacy  4200000
12      113      Mandy   240000
13      114    Bridget   757000
14      115    Crystal   560000

In [45]:
student={
    'name':['suman','bikash','ram'],
   'iq': [100,20,50],
    'merks':[300,21,11],
    'package':[322,22,4],
   
}
s=pd.DataFrame(student)
s.set_index('name', inplace=True)

In [46]:
s

         iq  merks  package
name
suman   100    300      322
bikash   20     21       22
ram      50     11        4

In [47]:
s.iloc[:]

         iq  merks  package
name
suman   100    300      322
bikash   20     21       22
ram      50     11        4

In [48]:
s.loc['suman']

iq         100
merks      300
package    322
Name: suman, dtype: int64

In [49]:
s.loc['suman':'ram']

         iq  merks  package
name
suman   100    300      322
bikash   20     21       22
ram      50     11        4

In [50]:
s.loc[['suman', 'ram']]

        iq  merks  package
name
suman  100    300      322
ram     50     11        4

In [51]:
employees.iloc[0:10]

,Index,User Id,First Name,Last Name,Sex,Email,Phone_no,Job Title,Salary
0,1,101,Shelby,Terrell,Male,elijah57@example.net,9803244242,Games developer,100000
1,2,102,Phillip,Summers,Female,bethany14@example.com,9808364778,Phytotherapist,200000
2,3,103,Kristine,Travis,Male,bthompson@example.com,9830238573,Homeopath,350000
3,4,104,Yesenia,Martinez,Male,kaitlinkaiser@example.com,9843028573,Market researcher,400000
4,5,105,Lori,Todd,Male,buchananmanuel@example.net,9732082954,Veterinary surgeon,230000
5,6,106,Erin,Day,Male,tconner@example.org,9807463847,Waste management officer,240000
6,7,107,Katherine,Buck,Female,conniecowan@example.com,9876056789,Intelligence analyst,200000
7,8,108,Ricardo,Hinton,Male,wyattbishop@example.com,7653456533,Hydrogeologist,23400
8,9,109,Dave,Farrell,Male,nmccann@example.net,9876890345,Lawyer,255555
9,10,110,Isaiah,Downs,Male,virginiaterrell@example.org,9086547543,"Engineer, site",332000

In [52]:
employees.iloc[[2,4,5]]

,Index,User Id,First Name,Last Name,Sex,Email,Phone_no,Job Title,Salary
2,3,103,Kristine,Travis,Male,bthompson@example.com,9830238573,Homeopath,350000
4,5,105,Lori,Todd,Male,buchananmanuel@example.net,9732082954,Veterinary surgeon,230000
5,6,106,Erin,Day,Male,tconner@example.org,9807463847,Waste management officer,240000

In [53]:
employees.iloc[1::2]

,Index,User Id,First Name,Last Name,Sex,Email,Phone_no,Job Title,Salary
1,2,102,Phillip,Summers,Female,bethany14@example.com,9808364778,Phytotherapist,200000
3,4,104,Yesenia,Martinez,Male,kaitlinkaiser@example.com,9843028573,Market researcher,400000
5,6,106,Erin,Day,Male,tconner@example.org,9807463847,Waste management officer,240000
7,8,108,Ricardo,Hinton,Male,wyattbishop@example.com,7653456533,Hydrogeologist,23400
9,10,110,Isaiah,Downs,Male,virginiaterrell@example.org,9086547543,"Engineer, site",332000
11,12,112,Stacy,Newton,Male,rayleroy@example.org,7543326534,Warden/ranger,4200000
13,14,114,Bridget,Nash,Female,mercedes44@example.com,2424552444,Social worker,757000

In [54]:
employees.iloc[:3,3:6]

  Last Name     Sex                  Email
0   Terrell    Male   elijah57@example.net
1   Summers  Female  bethany14@example.com
2    Travis    Male  bthompson@example.com

In [55]:
employees.loc[0:2,'Last Name':'Email']

  Last Name     Sex                  Email
0   Terrell    Male   elijah57@example.net
1   Summers  Female  bethany14@example.com
2    Travis    Male  bthompson@example.com

In [56]:
employees.loc[0::2,'Index'::2]

    Index First Name     Sex    Phone_no  Salary
0       1     Shelby    Male  9803244242  100000
2       3   Kristine    Male  9830238573  350000
4       5       Lori    Male  9732082954  230000
6       7  Katherine  Female  9876056789  200000
8       9       Dave    Male  9876890345  255555
10     11     Sheila  Female  5397852134  220000
12     13      Mandy    Male  3734672477  240000
14     15    Crystal    Male  2345455555  560000

In [57]:
ipl=pd.read_csv('ipl-matches.csv')
ipl.head(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon

In [58]:
# find all the final winners

In [59]:
final_match=ipl[ipl['MatchNumber']=='Final']
final_match[['Season', 'WinningTeam']]

      Season            WinningTeam
0       2022         Gujarat Titans
74      2021    Chennai Super Kings
134  2020/21         Mumbai Indians
194     2019         Mumbai Indians
254     2018    Chennai Super Kings
314     2017         Mumbai Indians
373     2016    Sunrisers Hyderabad
433     2015         Mumbai Indians
492     2014  Kolkata Knight Riders
552     2013         Mumbai Indians
628     2012  Kolkata Knight Riders
702     2011    Chennai Super Kings
775  2009/10    Chennai Super Kings
835     2009        Deccan Chargers
892  2007/08       Rajasthan Royals

In [60]:
# how many super over finishes have occured

In [72]:
n=ipl[ipl['SuperOver']=='Y'].shape[0]
print("Total numbers of super over occured matches= ", n)

Total numbers of super over occured matches=  14

In [73]:
# how many matches has csk won in kolkata()

In [74]:
ipl[(ipl['WinningTeam']=='Chennai Super Kings') & (ipl['City']=='Kolkata')].shape[0]

5

In [75]:
# toss winner is match winner in percentage.

In [76]:
no_win=ipl[ipl['TossWinner']==ipl['WinningTeam']].shape[0]
(no_win/ipl.shape[0])*100

51.473684210526315

In [77]:
# movies with rating higher than 8 and votes>10000

mi=(ipl['Team1']=='Mumbai Indians') | (ipl['Team2']=='Mumbai Indians')
lose_mi=ipl['WinningTeam']!='Mumbai Indians'
ipl[mi&lose_mi]['Player_of_Match'].value_counts().head(1)
# ipl[
#     (
#         (ipl['Team1'] == 'Mumbai Indians') | 
#         (ipl['Team2'] == 'Mumbai Indians')
#     ) &
#     (ipl['WinningTeam'] != 'Mumbai Indians')
# ]['Player_of_Match'].value_counts().head(1)

Player_of_Match
SPD Smith    4
Name: count, dtype: int64

In [78]:
ipl['Player_of_Match'].value_counts().head(1)

Player_of_Match
AB de Villiers    25
Name: count, dtype: int64

In [79]:
# Action movies with rating higher than 7.5

In [80]:
# write a function that can return the track record of 2 teams against each other

In [81]:
ipl.sort_values('City', na_position='first')

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
134,1237181,NaN,2020-11-10,2020/21,Final,Delhi Capitals,Mumbai Indians,Dubai International Cricket Stadium,Delhi Capitals,bat,N,Mumbai Indians,Wickets,5.0,NaN,TA Boult,"['MP Stoinis', 'S Dhawan', 'AM Rahane', 'SS Iy...","['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...",CB Gaffaney,Nitin Menon
137,1237177,NaN,2020-11-05,2020/21,Qualifier 1,Mumbai Indians,Delhi Capitals,Dubai International Cricket Stadium,Delhi Capitals,field,N,Mumbai Indians,Runs,57.0,NaN,JJ Bumrah,"['Q de Kock', 'RG Sharma', 'SA Yadav', 'Ishan ...","['PP Shaw', 'S Dhawan', 'AM Rahane', 'SS Iyer'...",CB Gaffaney,Nitin Menon
138,1216495,NaN,2020-11-03,2020/21,56,Mumbai Indians,Sunrisers Hyderabad,Sharjah Cricket Stadium,Sunrisers Hyderabad,field,N,Sunrisers Hyderabad,Wickets,10.0,NaN,S Nadeem,"['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...","['DA Warner', 'WP Saha', 'MK Pandey', 'KS Will...",C Shamshuddin,RK Illingworth
140,1216530,NaN,2020-11-01,2020/21,54,Kolkata Knight Riders,Rajasthan Royals,Dubai International Cricket Stadium,Rajasthan Royals,field,N,Kolkata Knight Riders,Runs,60.0,NaN,PJ Cummins,"['Shubman Gill', 'N Rana', 'RA Tripathi', 'SP ...","['RV Uthappa', 'BA Stokes', 'SPD Smith', 'SV S...",Nitin Menon,PR Reiffel
142,1216535,NaN,2020-10-31,2020/21,51,Delhi Capitals,Mumbai Indians,Dubai International Cricket Stadium,Mumbai Indians,field,N,Mumbai Indians,Wickets,9.0,NaN,Ishan Kishan,"['PP Shaw', 'S Dhawan', 'SS Iyer', 'RR Pant', ...","['Ishan Kishan', 'Q de Kock', 'SA Yadav', 'SS ...",YC Barde,PR Reiffel
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,1181766,Visakhapatnam,2019-05-08,2019,Eliminator,Sunrisers Hyderabad,Delhi Capitals,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Delhi Capitals,field,N,Delhi Capitals,Wickets,2.0,NaN,RR Pant,"['WP Saha', 'MJ Guptill', 'MK Pandey', 'KS Wil...","['PP Shaw', 'S Dhawan', 'SS Iyer', 'RR Pant', ...",BNJ Oxenford,S Ravi
195,1181767,Visakhapatnam,2019-05-10,2019,Qualifier,Delhi Capitals,Chennai Super Kings,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Chennai Super Kings,field,N,Chennai Super Kings,Wickets,6.0,NaN,F du Plessis,"['PP Shaw', 'S Dhawan', 'C Munro', 'SS Iyer', ...","['F du Plessis', 'SR Watson', 'SK Raina', 'AT ...",BNJ Oxenford,S Ravi
472,829743,Visakhapatnam,2015-04-22,2015,19,Sunrisers Hyderabad,Kolkata Knight Riders,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Kolkata Knight Riders,field,N,Sunrisers Hyderabad,Runs,16.0,D/L,DA Warner,"['S Dhawan', 'DA Warner', 'RS Bopara', 'NV Ojh...","['RV Uthappa', 'G Gambhir', 'MK Pandey', 'AD R...",RK Illingworth,VA Kulkarni
380,981005,Visakhapatnam,2016-05-21,2016,53,Rising Pune Supergiants,Kings XI Punjab,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Kings XI Punjab,bat,N,Rising Pune Supergiants,Wickets,4.0,NaN,MS Dhoni,"['AM Rahane', 'UT Khawaja', 'GJ Bailey', 'SS T...","['HM Amla', 'M Vijay', 'WP Saha', 'Gurkeerat S...",HDPK Dharmasena,Nitin Menon
384,980997,Visakhapatnam,2016-05-17,2016,49,Rising Pune Supergiants,Delhi Daredevils,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Rising Pune Supergiants,field,N,Rising Pune Supergiants,Runs,19.0,D/L,AB Dinda,"['AM Rahane', 'UT Khawaja', 'GJ Bailey', 'SS T...","['Q de Kock', 'SS Iyer', 'KK Nair', 'SV Samson...",Nitin Menon,C Shamshuddin

In [82]:
batsman=pd.read_csv('batsman_runs_ipl.csv')
batsman.head(5)

           batter  batsman_run
0  A Ashish Reddy          280
1        A Badoni          161
2      A Chandila            4
3        A Chopra           53
4     A Choudhary           25

In [83]:
batsman['batsman_rank']=batsman['batsman_run'].rank(ascending=False)
batsman.sort_values('batsman_rank')

           batter  batsman_run  batsman_rank
569       V Kohli         6634           1.0
462      S Dhawan         6244           2.0
130     DA Warner         5883           3.0
430     RG Sharma         5881           4.0
493      SK Raina         5536           5.0
..            ...          ...           ...
512   SS Cottrell            0         594.0
466     S Kaushik            0         594.0
203     IC Pandey            0         594.0
467       S Ladda            0         594.0
468  S Lamichhane            0         594.0

[605 rows x 3 columns]

In [84]:
batsman.set_index('batter')

                batsman_run  batsman_rank
batter
A Ashish Reddy          280         166.5
A Badoni                161         226.0
A Chandila                4         535.0
A Chopra                 53         329.0
A Choudhary              25         402.5
...                     ...           ...
Yash Dayal                0         594.0
Yashpal Singh            47         343.0
Younis Khan               3         547.5
Yuvraj Singh           2754          27.0
Z Khan                  117         256.0

[605 rows x 2 columns]

In [85]:
batsman.set_index('batsman_rank')

                      batter  batsman_run
batsman_rank
166.5         A Ashish Reddy          280
226.0               A Badoni          161
535.0             A Chandila            4
329.0               A Chopra           53
402.5            A Choudhary           25
...                      ...          ...
594.0             Yash Dayal            0
343.0          Yashpal Singh           47
547.5            Younis Khan            3
27.0            Yuvraj Singh         2754
256.0                 Z Khan          117

[605 rows x 2 columns]

In [86]:
batsman

             batter  batsman_run  batsman_rank
0    A Ashish Reddy          280         166.5
1          A Badoni          161         226.0
2        A Chandila            4         535.0
3          A Chopra           53         329.0
4       A Choudhary           25         402.5
..              ...          ...           ...
600      Yash Dayal            0         594.0
601   Yashpal Singh           47         343.0
602     Younis Khan            3         547.5
603    Yuvraj Singh         2754          27.0
604          Z Khan          117         256.0

[605 rows x 3 columns]

In [87]:
batsman.rename(columns={'batter':'batter_name'}, inplace=True)
batsman

        batter_name  batsman_run  batsman_rank
0    A Ashish Reddy          280         166.5
1          A Badoni          161         226.0
2        A Chandila            4         535.0
3          A Chopra           53         329.0
4       A Choudhary           25         402.5
..              ...          ...           ...
600      Yash Dayal            0         594.0
601   Yashpal Singh           47         343.0
602     Younis Khan            3         547.5
603    Yuvraj Singh         2754          27.0
604          Z Khan          117         256.0

[605 rows x 3 columns]

In [88]:
batsman

        batter_name  batsman_run  batsman_rank
0    A Ashish Reddy          280         166.5
1          A Badoni          161         226.0
2        A Chandila            4         535.0
3          A Chopra           53         329.0
4       A Choudhary           25         402.5
..              ...          ...           ...
600      Yash Dayal            0         594.0
601   Yashpal Singh           47         343.0
602     Younis Khan            3         547.5
603    Yuvraj Singh         2754          27.0
604          Z Khan          117         256.0

[605 rows x 3 columns]

In [89]:
batsman.rename(index={'A Ashish Reddy':'Reddy'})

        batter_name  batsman_run  batsman_rank
0    A Ashish Reddy          280         166.5
1          A Badoni          161         226.0
2        A Chandila            4         535.0
3          A Chopra           53         329.0
4       A Choudhary           25         402.5
..              ...          ...           ...
600      Yash Dayal            0         594.0
601   Yashpal Singh           47         343.0
602     Younis Khan            3         547.5
603    Yuvraj Singh         2754          27.0
604          Z Khan          117         256.0

[605 rows x 3 columns]

In [90]:
ipl['City'].isnull().head(20)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: City, dtype: bool

In [91]:
ipl.drop_duplicates()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [92]:
ipl.head(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon

In [93]:
ipl['all_player']=ipl['Team1Players']+ipl['Team2Players']
ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,all_player
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ..."
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,...,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ..."
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,...,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ..."
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,...,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ..."
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,...,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,...,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G..."
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,...,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '..."
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,...,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa..."
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,...,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra..."
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis..."

In [94]:
#last game of v kohli played in delhi

In [96]:
ipl['is_kohli_played']=ipl['all_player'].apply(lambda x:'V Kohli' in x)
a=ipl[(ipl['City']=='Delhi')& (ipl['is_kohli_played']==True)]
a.drop_duplicates(subset=['City','is_kohli_played'],keep='last')

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,all_player,is_kohli_played
933,335998,Delhi,2008-04-30,2007/08,17,Delhi Daredevils,Royal Challengers Bangalore,Feroz Shah Kotla,Royal Challengers Bangalore,field,...,Runs,10.0,NaN,GD McGrath,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'Shoaib ...","['P Kumar', 'W Jaffer', 'LRPL Taylor', 'JH Kal...",Aleem Dar,I Shivram,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'Shoaib ...",True